name: A workflow for Group6 Coursework
on: push

jobs:
  build:
    name: Group6 Coursework action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -f semGroup6/pom.xml package
      - name: Build Docker Image
        run: docker build -t semimage ./semGroup6
      - name: Run image
        run: docker run --name semcontainer -d semimage
      - name: view logs
        run: docker logs semcontainer
